import csv

# open Players.csv file with csv.DictReader and read its content into a list of dictionary, players_data
players_data = []
with open('Players.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        players_data.append(r)

# open Teams.csv file with csv.DictReader and read its content into a list of dictionary, teams_data
teams_data = []
with open('Teams.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        teams_data.append(r)


def average_shots(players_data):
    """Returns a tuple with four elements; the first, second, third, and
    fourth elements show the average number of shots made by defenders,
    midfielders, forwards, and goalkeepers, respectively

    Notes: the test results below are printed out with two decimal places to
    get around floating-point errors.

    >>> averages = average_shots(players_data)
    >>> type(averages)
    <class 'tuple'>
    >>> [f'{a:.2f}' for a in averages]
    ['1.16', '2.39', '4.23', '0.03']
    """
    defend = [int(_dict['shots']) for _dict in players_data if _dict['position'] == 'defender']
    mid = [int(_dict['shots']) for _dict in players_data if _dict['position'] == 'midfielder']
    forward = [int(_dict['shots']) for _dict in players_data if _dict['position'] == 'forward']
    goal = [int(_dict['shots']) for _dict in players_data if _dict['position'] == 'goalkeeper']

    return sum(defend)/len(defend), sum(mid)/len(mid), sum(forward)/len(forward), sum(goal)/len(goal)


def max_GF_GA_ratio(teams_data):
    """Returns the string name of a team with highest ratio of goalsFor to
    goalsAgainst

    >>> max_GF_GA_ratio(teams_data)
    'Portugal'
    """
    high = 0
    team = ''
    for _dict in teams_data:
        score = int(_dict['goalsFor'])/int(_dict['goalsAgainst'])
        if score > high:
            high = score
            team = _dict['team']
    return team


def whose_player_list(players_data, teams_data):
    """Returns a list of tuples; each tuple has information about a player who
    is on a team ranked in the top 10, plays less than 250 minutes and makes
    more than 150 passes; the format for each tuple is (player's surname, team
    played for, team ranking, minutes played, number of passes)

    >>> whose_player_list(players_data, teams_data)
    [('Veron', 'Argentina', 7, 185, 235), ('Montolivo', 'Italy', 5, 236, 163)]
    """
    # Reminder: Convert minutes and passes to integers before comparing to values
    team_list = []
    for player_dict in players_data:
        for team_dict in teams_data:
            if int(team_dict['ranking']) <= 10 and player_dict['team'] == team_dict['team']:
                if int(player_dict['minutes']) < 250 and int(player_dict['passes']) > 150:
                    team = (player_dict['surname'], player_dict['team'], int(team_dict['ranking']),
                            int(player_dict['minutes']), int(player_dict['passes']))
                    team_list.append(team)

    return team_list


def team_list_shots_per_minute(players_data, teams_data):
    """Returns a list of tuples; each tuple has information about a team and
    its shots per minute value generated by its players

    Notes: the test results below are printed out with five decimal places to
    get around floating-point errors.

    >>> list_of_tuples = team_list_shots_per_minute(players_data, teams_data)
    >>> list_of_tuples.sort()
    >>> for team,shots in list_of_tuples:
    ...     print(f'{team} {shots:.5f}')
    ... 
    Algeria 0.01050
    Argentina 0.01394
    Australia 0.01010
    Brazil 0.01440
    Cameroon 0.01178
    Chile 0.01152
    Denmark 0.01077
    England 0.01237
    France 0.00998
    Germany 0.01121
    Ghana 0.01337
    Greece 0.01077
    Honduras 0.00438
    Italy 0.01212
    Ivory Coast 0.01313
    Japan 0.00886
    Mexico 0.01086
    Netherlands 0.01128
    New Zealand 0.00505
    Nigeria 0.00996
    North Korea 0.01077
    Paraguay 0.00928
    Portugal 0.01263
    Serbia 0.01286
    Slovakia 0.00884
    Slovenia 0.00572
    South Africa 0.01184
    South Korea 0.01111
    Spain 0.01380
    Switzerland 0.00721
    USA 0.01282
    Uruguay 0.01118
    """
    team_list = []
    for team_dict in teams_data:
        shot = []
        minute = []
        for player_dict in players_data:
            if player_dict['team'] == team_dict['team']:
                shot.append(int(player_dict['shots']))
                minute.append(int(player_dict['minutes']))

        avg = sum(shot)/sum(minute)
        emp_tup = (team_dict['team'], avg)
        team_list.append(emp_tup)

    return team_list


if __name__ == "__main__":
    import doctest
    doctest.testmod()
